### ISSUE TITLE
comfyui-refiners is a nightmare to install

### ISSUE THREAD

**Issue by martintomov** [finegrain-ai/refiners#475]
@deltheil Hi there! First, I want to commend you on creating an exceptional model that’s outperforming competitors. However, installing this node in ComfyUI has proven challenging for most Windows users. Despite following the installation steps, including requirements.txt, the process frequently fails, throwing import errors. Furthermore, installing refiners pulls in `numpy==1.24.4`, which breaks compatibility with several other custom nodes, leading to frustration among developers.

Several devs have voiced concerns about this, so it might be worth prioritizing a fix. Specifically, the imports in both `box_segmenter.py` and `grounding_dino.py` could use adjustments to bypass these issues and prevent the following recurring error messages in ComfyUI logs:

**Error Traceback 1:**
```
Traceback (most recent call last):
  File "C:\Users\Admin\comfyui\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\custom_nodes\comfyui-refiners\__init__.py", line 3, in <module>
    from .box_segmenter import NODE_CLASS_MAPPINGS as box_segmenter_mappings
  File "C:\Users\Admin\custom_nodes\comfyui-refiners\box_segmenter.py", line 5, in <module>
    from refiners.fluxion.utils import image_to_tensor, no_grad, tensor_to_image
ModuleNotFoundError: No module named 'refiners'
```
Even when refiners is indeed installed...:

**Error Traceback 2:**
```
Traceback (most recent call last):
  File "C:\Users\comfyui\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\custom_nodes\comfyui-refiners\__init__.py", line 3, in <module>
    from .box_segmenter import NODE_CLASS_MAPPINGS as box_segmenter_mappings
  File "C:\Users\custom_nodes\comfyui-refiners\box_segmenter.py", line 6, in <module>
    from refiners.solutions import BoxSegmenter as _BoxSegmenter
ModuleNotFoundError: No module named 'refiners.solutions'
```
Similar conversation and more debug details could be found in #472

**Comment by Laurent2916** [comment]
Hi @martintomov, as discussed on discord:

> we haven't tested the nodes on windows and we know the installation process has issues. We're unfortunately pretty busy on other unrelated things, though this has been bugging me for a while, so I'll try to somehow debug this in the following days.

**Comment by Laurent2916** [comment]
Alright, I dusted off my old windows laptop and successfully got comfyui working with our custom nodes:

![image](https://github.com/user-attachments/assets/617b648c-d764-484b-91b1-9d8c5917f7f1)

Now I simply need to check I can reproduce what I did (should be rather simple) and document the steps. Stay tuned.

**Comment by martintomov** [comment]
hey laurent, appreciate you putting in the work! quick question — what numpy version are you using for this? i ran into conflicts with nodes like layerstyle and mixlab when numpy==1.24.4 got pulled in from the refiners.git install. 

if you could keep these deps issues in mind when replicating the process, it’d be a great benchmark test for a real comfyui env. thanks!

**Comment by Laurent2916** [comment]
Okay, I did everything a second time, here is the steps I did:

1. Install python (e.g. via winget: https://winget.run/pkg/Python/Python.3.11)

2. Install git (e.g. via winget: https://winget.run/pkg/Git/Git)

3. Create a directory where I'll install everything:
```
PS C:\Users\Laurent\Documents> mkdir comfy
PS C:\Users\Laurent\Documents> cd comfy
```

4. (Optional) Create a python virtual environment, to not install everything globally:
```
PS C:\Users\Laurent\Documents\comfy> python -m venv .venv
PS C:\Users\Laurent\Documents\comfy> .\.venv\Scripts\activate
```

5. Install comfy-cli:
```
(.venv) PS C:\Users\Laurent\Documents\comfy> pip install comfy-cli
```

6. Setup ComfyUI:
```
(.venv) PS C:\Users\Laurent\Documents\comfy> comfy --here install
```

7. Install the comfyui-refiners custom nodes:
```
(.venv) PS C:\Users\Laurent\Documents\comfy> comfy node registry-install comfyui-refiners
```

8. Ensure that comfyui-refiners's dependencies are installed (from what I observed in the source code of comfy-cli, this isn't handled correctly):
```
(.venv) PS C:\Users\Laurent\Documents\comfy> pip install -r .\ComfyUI\custom_nodes\comfyui-refiners\requirements.txt
```

9. Start ComfyUI:
```
(.venv) PS C:\Users\Laurent\Documents\comfy> comfy launch
```

**Comment by martintomov** [comment]
@Laurent2916 Thank you for your work once again! It works like a charm.
